version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: The_ManWhoS0ldTheWor1d
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://admin:The_ManWhoS0ldTheWor1d@db:5432/market_db
    restart: always

volumes:
  postgres_data: