"""Initial schema

Revision ID: 796c61a169ad
Revises: 
Create Date: 2025-05-04 15:50:09.722345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
#from alembic.ddl import postgresql

# revision identifiers, used by Alembic.
revision: str = '796c61a169ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),

                    sa.CheckConstraint("ticker ~ '^[A-Z]{2,10}$'", name='check_ticker_format'),
                    sa.PrimaryKeyConstraint('ticker')
                    )

    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),

                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), nullable=False),
                    sa.Column('api_key', sa.String(), nullable=False),

                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('balances',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('frozen_amount', sa.Integer(), nullable=False),

                    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),

                    sa.CheckConstraint("frozen_amount <= amount", name='check_frozen_le_amount'),
                    sa.PrimaryKeyConstraint('user_id', 'ticker'),
                    sa.UniqueConstraint('user_id', 'ticker', name='uq_user_ticker')
                    )

    op.create_table('deposits',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.CheckConstraint('amount > 0', name='check_deposit_amount_positive'),
                    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('limit_orders',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),

                    sa.Column('direction', sa.Enum('BUY', 'SELL', name='direction'), nullable=False),
                    sa.Column('qty', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('status',
                              sa.Enum('NEW', 'EXECUTED', 'PARTIALLY_EXECUTED', 'CANCELLED', name='order_status'),
                              nullable=False),
                    sa.Column('filled', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),

                    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('market_orders',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),

                    sa.Column('direction', sa.Enum('BUY', 'SELL', name='direction'), nullable=False),
                    sa.Column('qty', sa.Integer(), nullable=False),
                    sa.Column('rate', sa.Integer(), nullable=False),
                    sa.Column('status',
                              sa.Enum('NEW', 'EXECUTED', 'PARTIALLY_EXECUTED', 'CANCELLED', name='order_status'),
                              nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),

                    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),

                    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)

    op.create_table('withdrawals',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.CheckConstraint('amount > 0', name='check_withdrawal_amount_positive'),
                    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('asset_equivalents',
                    sa.Column('base_ticker', sa.String(), nullable=False),
                    sa.Column('equivalent_ticker', sa.String(), nullable=False),
                    sa.Column('rate', sa.Integer(), nullable=False),

                    sa.ForeignKeyConstraint(['base_ticker'], ['instruments.ticker'], ),
                    sa.ForeignKeyConstraint(['equivalent_ticker'], ['instruments.ticker'], ),

                    sa.PrimaryKeyConstraint('base_ticker', 'equivalent_ticker'),
                    sa.UniqueConstraint('base_ticker', 'equivalent_ticker', name='eq_base_ticker')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('market_orders')
    op.drop_table('limit_orders')
    op.drop_table('deposits')
    op.drop_table('balances')
    op.drop_table('users')
    op.drop_table('instruments')
    op.drop_table('asset_equivalents')
    # ### end Alembic commands ###
